version: "3"
services:
  app:
    build: ./docker/flask
    volumes:
      - .:/app
      - socket:/tmp
    command: uwsgi --ini  app.ini
    # ports:
    #   - 5000:5000
    depends_on:
      - db
    tty: true
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: flask_dev
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
      - socket:/tmp
volumes:
  mysql-data:
  socket:
